name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: digitalpatterns/jdk/master
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        snapshot: true
        tags: "latest, ${{ github.sha }}"
